language: python
dist: bionic
cache:
  pip: true
  directories:
    - $HOME/nest-$NEST_VERSION
jobs:
  include:
    python: 3.6.9
install:
  - export NEST_INSTALL_DIR=/home/travis/nest-$NEST_VERSION
  - source devops/check_nest_cache.sh
  - sudo apt-get install -y python3.6-dev libpython3.6-dev python3-rtree build-essential cmake cython libgsl-dev libltdl-dev libncurses-dev libreadline-dev openmpi-bin libopenmpi-dev python3-numpy python3-scipy python3-matplotlib
  - if [ "$HAS_NEST_CACHE" = "0" ]; then
      source devops/install_nest.sh
    else
      echo "NEST cache found, skipping installation";
    fi
  - export PYTHON_PATH=/home/travis/nest-=NEST_VERSION/lib/python3.6/site-packages:$PYTHON_PATH
  - python -m pip install .
script:
  - python -c "import nest; nest.Install('cerebmodule')"
